name: github pages

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '10.x'
  PYTHON_VERSION: '3.9'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout Submodules
        run: git submodule update --remote --recursive
      - name: use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ env.NODE_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y tidy optipng locales
          python -m pip install --upgrade pip
          pip install virtualenv
          make setup
      - name: Build
        run: |
          make translate-config site SITE=src/site-prod.yml
          make optimize-html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build